typography_spectrum: 0.7085586949251592
color:
  brandStrength: 0.3553830669261515
  lightness: 0.6457988535985351
  saturation: 0.8308365216944367
  rhythmicContrast: 0.9669470833614469
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.2557283607311547
author:
  name: David Braunstein
  email: davidbraunstein@bigpond.com
  url: theserendipityinstitute.com
name: The Serendipity Institute
title: learning by accidental insight
